KNOWS = "KNOWS"
LOVES = "LOVES"
BETRAYED = "BETRAYED"
ALLIED_WITH = "ALLIED_WITH"
CAUSED = "CAUSED"
VISITED = "VISITED"
PARTICIPATED_IN = "PARTICIPATED_IN"
OCCURRED_AT = "OCCURRED_AT"
OWNS = "OWNS"

RELATIONSHIP_TYPES = frozenset(
    {
        KNOWS,
        LOVES,
        BETRAYED,
        ALLIED_WITH,
        CAUSED,
        VISITED,
        PARTICIPATED_IN,
        OCCURRED_AT,
        OWNS,
    }
)
